### ISSUE TITLE
Practice exercise 

### ISSUE THREAD

**Issue by KlausChen117** [BraedonWooding/Comp2521-19T3#1]
Hey:
Thank you for your contribution to the practice exercise answers. With the answers you provided, the mid-term exam was very good. I would like to know whether you will upload the answer of the practice exercise of Graphs for our reference?
Thanks

**Comment by BraedonWooding** [comment]
@KlausChen117 Ashesh doesn't want us to give away any solutions for the graph exercises so I won't be able to.

Feel free to email me if you need help with a particular one.
